package models

case class tlclass(chapter: String,
                   rep: String,
                   tyear: String,
                   curr: String,
                   hsrep: String,
                   flow: String,
                   repcurr: String,
                   comm: String,
                   prt: String,
                   weight: String,
                   qty: String,
                   qunit: String,
                   tvalue: String,
                   est: String,
                   ht: String)

// case class tlclass(chapter: String,
//                    rep: String,
//                    tyear: String,
//                    curr: String,
//                    hsrep: String,
//                    flow: String,
//                    repcurr: String,
//                    comm: String,
//                    prt: String,
//                    weight: Double,
//                    qty: Double,
//                    qunit: String,
//                    tvalue: Double,
//                    est: String,
//                    ht: String)
